namespace PaketLoadScripts

#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\Microsoft.Build.Framework.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\Microsoft.Build.Utilities.Core.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\Microsoft.Win32.Registry.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.CodeDom.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Collections.Immutable.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Reflection.Metadata.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Reflection.TypeExtensions.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Resources.Extensions.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Security.Cryptography.Pkcs.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Security.Cryptography.Xml.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Security.Permissions.fsx" 
#load "C:\\Users\\beauv\\fs\\tmp\\WaypointClean\\.paket\\load\\netcoreapp3.0\\Docs\\System.Threading.Tasks.Dataflow.fsx" 
#r "C:\\Users\\beauv\\.nuget\\packages\\microsoft.build.tasks.core\\16.8.0\\lib\\netstandard2.0\\Microsoft.Build.Tasks.Core.dll" 